# SPDX-License-Identifier: MPL-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        additional_dependencies: []
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML", "types-requests", "types-setuptools"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-q", "-r", "src"]
  - repo: local
    hooks:
      - id: add-spdx-headers
        name: add SPDX headers
        entry: tools/add_spdx_headers.py
        language: python
        types_or: [python, shell, yaml, toml, markdown, makefile]
        pass_filenames: true
      - id: commitlint
        name: commitlint
        entry: scripts/commitlint
        language: system
        stages: [commit-msg]
