# config/risk_alignment.yaml
risk_profiles:
  aggressive:
    target_vol_annual: 0.22        # 22% annualized volatility target
    target_cvar_95_annual: 0.28    # 95% CVaR; annualized loss tail budget
    tolerance:
      vol_abs: 0.02                # allowable absolute dev in vol
      cvar_abs: 0.03               # allowable absolute dev in CVaR
    guardrail:
      max_under_risk_vol: 0.04     # if vol is >4% below target for N months, escalate
      window_months: 3
    primal_dual:
      lambda_init: 1.0
      step: 0.25
      clamp: [0.0, 100.0]
  moderate:
    target_vol_annual: 0.14
    target_cvar_95_annual: 0.18
    tolerance: { vol_abs: 0.015, cvar_abs: 0.02 }
    primal_dual: { lambda_init: 1.0, step: 0.25, clamp: [0.0, 100.0] }
  conservative:
    target_vol_annual: 0.07
    target_cvar_95_annual: 0.10
    tolerance: { vol_abs: 0.01, cvar_abs: 0.015 }
    primal_dual: { lambda_init: 1.0, step: 0.25, clamp: [0.0, 100.0] }

simulation:
  annualization_factor: 12         # monthly bars
  benchmark_symbol: "AGGR_IDX"     # synthetic "aggressive benchmark" for A/B
  seed: 1337

escalation:
  human_in_the_loop: true
  when_risk_delta_exceeds: 0.02     # trigger review when risk gap breaches 2% vol
