# SPDX-License-Identifier: MPL-2.0

# config/community_health.yaml
targets:
  # Engagement & retention
  dau_norm:        { lower: 0.45, upper: 0.70 }
  newcomer_ret_7:  { lower: 0.30, upper: 0.55 }
  newcomer_ret_30: { lower: 0.20, upper: 0.40 }
  reply_depth:     { lower: 1.8,  upper: 3.5 }
  # Diversity & voice
  topic_entropy:   { lower: 2.2,  upper: 3.5 }
  cohort_evenness: { lower: 0.85, upper: 1.15 }
  voice_loss_idx:  { lower: 0.00, upper: 0.08 }
  # Appeals & latency
  appeal_rate:     { lower: 0.02, upper: 0.10 }
  appeal_success:  { lower: 0.20, upper: 0.50 }
  reinstate_latency_days: { lower: 0.0, upper: 2.0 }
guardrails:
  harm_rate_max: 0.02
  fp_rate_max:   0.04
  gray_band:     0.10
  update_step:   0.15
  per_cohort_thresholds: true
cohorts:
  - "newcomer"
  - "debate_heavy"
  - "art_share"
  - "tech_help"
  - "general"
