# SPDX-License-Identifier: MPL-2.0

# Configuration for target LLM models
# This file would define API endpoints, keys (or references to secure storage),
# and other model-specific parameters.
default_model:
  name: "gpt-oss-20b"
  api_endpoint: "https://api.example.com/gpt-oss-20b/v1"
  api_key: "your_secret_key_here" # In a real system, use environment variables or secret management.
  provider_contact_info: "security@example.com"
