# SPDX-License-Identifier: MPL-2.0

# config/quality_budget.yaml
defaults:
  language: "python"
  sloc_max: 500                 # per module
  fn_length_max: 60             # lines; hard cap for any single function
  avg_fn_length_max: 35         # average lines per function
  cyclomatic_per_fn_max: 10     # McCabe per function
  cyclomatic_module_max: 80     # aggregate cap
  nesting_depth_max: 3          # maximum control-flow nesting
  duplication_pct_max: 0.08     # token-shingle duplication ratio
  import_count_max: 20          # direct dependencies per module
  docstring_coverage_min: 0.6   # fraction of public funcs/classes with docstrings
  mi_min: 65                    # maintainability index proxy (0..100)
  perf_time_budget_ms: 50       # optional microbench target per task case
  perf_space_budget_mb: 64
  bigo_target: "O(N log N)"     # declared target; empirically verified
  escalation:
    human_in_the_loop: true
    window_commits: 3           # persistently over budget → require review
overrides:
  # task-specific exceptions go here
