#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/_common.sh"

pip-compile --resolver=backtracking --upgrade --output-file requirements/base.txt requirements/base.in
pip-compile --resolver=backtracking --upgrade --output-file requirements/dev.txt requirements/dev.in
